### ISSUE TITLE
Game mechanic: Key mapping handler

### ISSUE THREAD

**Issue by ankanx** [o92design/Ericsson_LDJ_45#20]
**Is your feature request related to a problem? Please describe.**
We want the controlls of the game to be ambigious and up to the player and thus all fucntionality should be able to be mapped on imput.

**Describe the solution you'd like**
A imput handler script keeping track and assigning / scrambling the keys needed to trigger events. also public variables showing keys mapped to what.

**Comment by Haxxflaxx** [comment]
Anything more that is needed?
